# Coverity thin client with CNC scan farm on a GitHub-hosted ephemeral runner
name: cnc-thin-client

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  coverity:
    runs-on: macos-latest

    env:
      #COV_URL: ${{ secrets.COV_URL }}
      COV_URL: https://cnc.chuckaude.com
      COV_USER: ${{ secrets.COV_USER }}
      COVERITY_PASSPHRASE: ${{ secrets.COVERITY_PASSPHRASE }}
      COV_STREAM: igoat-swift-master
      BLDCMD: xcodebuild -UseModernBuildSystem=NO -workspace iGoat-Swift/iGoat-Swift.xcodeproj/project.xcworkspace -scheme iGoat-Swift build CODE_SIGNING_ALLOWED=NO

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Coverity Download
      run: |
        PLATFORM=macosx
        VERSION=2022.3.0
        curl -fLsS $COV_URL/api/v2/scans/downloads/cov_thin_client-$PLATFORM-$VERSION.tar.gz | tar -C $RUNNER_TEMP -xzf -
    - name: Coverity Full Scan
      run: |
        export PATH=$PATH:$RUNNER_TEMP/bin
        export COVERITY_CLI_ANALYSIS_LOCATION=cloud
        export COVERITY_CLI_CLOUD_ANALYSIS_ASYNC=false
        coverity scan -o commit.connect.url=$COV_URL -o commit.connect.stream=$COV_STREAM -- $BLDCMD
